# Generated by Django 6.0.4 on 2026-04-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=20)),
                ('math_grade', models.IntegerField()),
                ('physics_grade', models.IntegerField()),
                ('programming_grade', models.IntegerField()),
            ],
        ),
    ]
